// src/routes/privacy/+page.svelte
<script lang="ts">
	import Seo from '#lib/components/Seo.svelte';
</script>

<Seo
	title="Privacy policy, Elbi GradeSim"
	description="How Elbi GradeSim handles your data. Grades stay in your browser, in the web app's local storage or the extension's storage. Nothing is uploaded."
	path="/privacy/"
/>

<div class="wrap">
	<header class="page-head">
		<p class="eyebrow">Legal</p>
		<h1>Privacy policy</h1>
		<p>Last updated October 6, 2026</p>
	</header>

	<article class="prose">
		<h2>What Elbi GradeSim is</h2>
		<p>
			Elbi GradeSim is a free web app at gradesim.uplb.tools and a companion browser extension. Both help UPLB students compute
			their GWA, simulate Latin honor targets and plan their remaining terms. They are open source projects maintained by
			student volunteers under UPLB Tools, and they are not an official UPLB product.
		</p>

		<h2>Your grades stay in your browser</h2>
		<p>
			<strong>The web app saves your grades, settings and plan in your browser’s local storage on this device.</strong> It does
			not send your grades, GWA or plan to any server. All computation happens in your browser.
		</p>
		<ul>
			<li>No account or sign-up.</li>
			<li>No analytics, tracking or advertising scripts in the app.</li>
			<li>No cloud sync. Clearing your browser data, or using Clear my data on the Grades tab, removes what was saved.</li>
			<li>Backups and plan files you export are saved as files on your device, and you decide where they go.</li>
		</ul>

		<h2>The extension</h2>
		<p>
			The extension reads the grades AMIS already shows you when you open it while logged in, and keeps them in the
			extension’s storage on your device. It does not send your AMIS credentials, grades or GWA anywhere. It only runs on AMIS
			pages and, so that it can hand your grades to this web app when you ask, on gradesim.uplb.tools.
		</p>
		<p>
			When you choose Import from the GradeSim extension, the extension passes your grades directly to this page inside your
			browser. They do not travel over the network.
		</p>

		<h2>Hosting</h2>
		<p>
			The site is served by a hosting provider (currently Vercel), which may log standard request details such as IP address,
			browser and time of visit for security and delivery. Those logs never contain your grades, because your grades are not
			sent with any request. After the first visit the app can run offline from your browser’s cache.
		</p>

		<h2>Browser store listings</h2>
		<p>
			When you install the extension from the Chrome Web Store, Firefox Add-ons or Edge Add-ons, those platforms may collect
			installation and usage statistics under their own privacy policies. We only see aggregate install counts.
		</p>

		<h2>Open source</h2>
		<p>
			The source code for the web app and the extension is public on GitHub, so you can check how data is handled.
			Curriculum contributions in the repository never include anyone’s grades.
		</p>

		<h2>Children</h2>
		<p>Elbi GradeSim is meant for UPLB students and is not directed at children under 13.</p>

		<h2>Changes</h2>
		<p>We will update this policy if the app or the extension changes how data is handled. The date above shows the latest revision.</p>

		<h2>Contact</h2>
		<p>
			Questions? Email <a href="mailto:semariquit@gmail.com">semariquit@gmail.com</a> or open an issue on
			<a href="https://github.com/uplbtools/gradesim/issues" rel="noopener" target="_blank">GitHub</a>.
		</p>
	</article>
</div>

// app/privacy/page.jsx
import Link from "next/link";
import styles from "../legal.module.css";

export const metadata = {
  title: "Privacy Policy — Elbi GradeSim",
  description:
    "How Elbi GradeSim handles your data. Grade data stays on your device in the browser extension.",
};

export default function PrivacyPage() {
  return (
    <main className={styles.legalPage}>
      <Link href="/" className={styles.backLink}>
        ← Back to Elbi GradeSim
      </Link>

      <header className={styles.legalHeader}>
        <p className={styles.legalEyebrow}>Legal</p>
        <h1 className={styles.legalTitle}>Privacy Policy</h1>
        <p className={styles.legalUpdated}>Last updated: July 4, 2026</p>
      </header>

      <article className={styles.legalBody}>
        <section>
          <h2>What Elbi GradeSim is</h2>
          <p>
            Elbi GradeSim is a free browser extension that reads your grades from
            AMIS (amis.uplb.edu.ph) and helps UPLB students calculate GWA and simulate
            Latin honor targets. This website (gradesim) promotes and documents the
            extension. The extension and this site are open-source projects maintained
            by volunteers — not an official UPLB product.
          </p>
        </section>

        <section>
          <h2>The extension: your data stays local</h2>
          <p>
            <strong>
              All grade data captured by the Elbi GradeSim extension remains on your
              device.
            </strong>{" "}
            The extension stores courses, grades, and simulation settings in your
            browser&apos;s local storage. It does not send your AMIS credentials, grades,
            or GWA to any external server operated by Elbi GradeSim.
          </p>
          <ul>
            <li>No account sign-up required.</li>
            <li>No analytics or telemetry in the extension.</li>
            <li>No cloud sync — uninstalling or clearing browser data removes stored grades.</li>
            <li>
              The extension only interacts with AMIS pages you open; it does not run in
              the background on unrelated sites.
            </li>
          </ul>
        </section>

        <section>
          <h2>This website</h2>
          <p>
            Visiting this marketing site is separate from using the extension. The site
            may be hosted on Vercel or similar infrastructure, which can log standard
            request metadata (IP address, user agent, timestamps) for security and
            delivery. This site does not collect your grades or AMIS login.
          </p>
        </section>

        <section>
          <h2>Browser store listings</h2>
          <p>
            When you install from the Chrome Web Store, Firefox Add-ons, or Edge
            Add-ons, those platforms may collect installation and usage statistics
            according to their own privacy policies. Elbi GradeSim does not receive
            your personal identity from those stores beyond aggregate install counts.
          </p>
        </section>

        <section>
          <h2>Open source</h2>
          <p>
            Source code is available on GitHub. You can inspect how data is handled
            before installing. Community curriculum contributions are public in the
            repository and do not include your personal grades.
          </p>
        </section>

        <section>
          <h2>Children</h2>
          <p>
            The extension is intended for UPLB students. It is not directed at children
            under 13.
          </p>
        </section>

        <section>
          <h2>Changes</h2>
          <p>
            We may update this policy if the extension or website changes materially.
            The date above reflects the latest revision.
          </p>
        </section>

        <section>
          <h2>Contact</h2>
          <p>
            Questions? Email{" "}
            <a href="mailto:semariquit@gmail.com">semariquit@gmail.com</a> or open an
            issue on GitHub.
          </p>
        </section>
      </article>
    </main>
  );
}
