// app/terms/page.jsx
import Link from "next/link";
import styles from "../legal.module.css";

export const metadata = {
  title: "Terms of Service — Elbi GradeSim",
  description: "Terms for using the Elbi GradeSim browser extension and website.",
};

export default function TermsPage() {
  return (
    <main className={styles.legalPage}>
      <Link href="/" className={styles.backLink}>
        ← Back to Elbi GradeSim
      </Link>

      <header className={styles.legalHeader}>
        <p className={styles.legalEyebrow}>Legal</p>
        <h1 className={styles.legalTitle}>Terms of Service</h1>
        <p className={styles.legalUpdated}>Last updated: July 4, 2026</p>
      </header>

      <article className={styles.legalBody}>
        <section>
          <h2>Agreement</h2>
          <p>
            By installing Elbi GradeSim or using this website, you agree to these
            Terms. If you do not agree, do not use the extension or site.
          </p>
        </section>

        <section>
          <h2>What the extension does</h2>
          <p>
            Elbi GradeSim reads grade information displayed on AMIS pages you visit
            and performs local calculations (GWA, honor simulations, curriculum
            planning). It is a student tool — not an official UPLB or AMIS service.
            Calculations are estimates; verify important academic decisions with your
            college secretary or registrar.
          </p>
        </section>

        <section>
          <h2>Acceptable use</h2>
          <ul>
            <li>Use the extension only for your own academic planning.</li>
            <li>Do not tamper with AMIS or attempt to scrape data beyond normal browsing.</li>
            <li>Do not redistribute modified builds that misrepresent the project.</li>
            <li>Curriculum files you contribute to GitHub should not include personal grades.</li>
          </ul>
        </section>

        <section>
          <h2>No warranty</h2>
          <p>
            The extension and website are provided &quot;as is&quot; without warranties.
            GWA formulas, honor cutoffs, and curriculum data may be incomplete or
            outdated. Authors are not liable for academic decisions based on extension
            output.
          </p>
        </section>

        <section>
          <h2>AMIS and UPLB</h2>
          <p>
            AMIS is operated by UPLB. Elbi GradeSim is not affiliated with or endorsed
            by the university. Follow AMIS terms of use when accessing your account.
          </p>
        </section>

        <section>
          <h2>Open source license</h2>
          <p>
            The project is distributed under its repository license. Forking and
            contributions are welcome subject to that license and project guidelines.
          </p>
        </section>

        <section>
          <h2>Changes</h2>
          <p>
            These Terms may be updated. Continued use after changes means you accept
            the revised Terms.
          </p>
        </section>

        <section>
          <h2>Contact</h2>
          <p>
            Questions? Email{" "}
            <a href="mailto:semariquit@gmail.com">semariquit@gmail.com</a>.
          </p>
        </section>
      </article>
    </main>
  );
}

// src/routes/terms/+page.svelte
<script lang="ts">
	import Seo from '#lib/components/Seo.svelte';
</script>

<Seo
	title="Terms of use, Elbi GradeSim"
	description="Terms for using the Elbi GradeSim web app and browser extension. Calculations are estimates and the tool is not affiliated with UPLB."
	path="/terms/"
/>

<div class="wrap">
	<header class="page-head">
		<p class="eyebrow">Legal</p>
		<h1>Terms of use</h1>
		<p>Last updated October 6, 2026</p>
	</header>

	<article class="prose">
		<h2>Agreement</h2>
		<p>By using the Elbi GradeSim web app or installing the extension, you agree to these terms. If you do not agree, please do not use them.</p>

		<h2>What Elbi GradeSim does</h2>
		<p>
			The web app computes your GWA, honor targets and a course plan from grades you import or enter, entirely in your browser.
			The extension reads grade information shown on AMIS pages you visit and stores it on your device. Neither is an official
			UPLB or AMIS service.
		</p>

		<h2>Estimates, not records</h2>
		<p>
			GWA figures, honor simulations, offerings and graduation terms are estimates. Formulas, cutoffs and curriculum data may
			be incomplete or out of date. Verify important academic decisions with your college secretary or the Office of the
			University Registrar.
		</p>

		<h2>Your data</h2>
		<p>
			Your grades are saved in your browser and you are responsible for them. Clearing your browser data or using Clear my data
			removes them, and we cannot recover them for you. Export a backup if you want a copy.
		</p>

		<h2>Acceptable use</h2>
		<ul>
			<li>Use Elbi GradeSim for your own academic planning.</li>
			<li>Do not tamper with AMIS or try to collect data beyond normal browsing.</li>
			<li>Do not redistribute modified builds in a way that misrepresents the project.</li>
			<li>Keep personal grades out of curriculum files you contribute on GitHub.</li>
		</ul>

		<h2>No warranty</h2>
		<p>
			The web app and the extension are provided as is, without warranties of any kind. The authors are not liable for academic
			decisions made from their output.
		</p>

		<h2>UPLB and AMIS</h2>
		<p>
			AMIS is operated by UPLB. Elbi GradeSim is not affiliated with or endorsed by the University of the Philippines Los
			Baños or the UP System. UP and UPLB marks belong to the UP System. Follow the AMIS terms of use when you access your
			account.
		</p>

		<h2>Open source license</h2>
		<p>The project is distributed under the license in its repository. Forks and contributions are welcome under that license and the project guidelines.</p>

		<h2>Changes</h2>
		<p>These terms may change. Continuing to use Elbi GradeSim after a change means you accept the revised terms.</p>

		<h2>Contact</h2>
		<p>Questions? Email <a href="mailto:semariquit@gmail.com">semariquit@gmail.com</a>.</p>
	</article>
</div>
